### ISSUE TITLE
ViewDestroyedError thrown when using Grid's filter menu

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-angular#1223]
The error appears whenever the Grid's filter menu opens upwards (on top of the grid) and then we try to close it or open another filter menu.

Check the following sample plunker demonstrating the issue:

[https://plnkr.co/edit/ULw0AIJj9Q8opZbWT1Bt?p=preview](https://plnkr.co/edit/ULw0AIJj9Q8opZbWT1Bt?p=preview)

**Comment by ilianiv** [comment]
All popups (in compobox, dropdownlist, etc...) in our application throws the same error on close when they were opened upwards. I've noticed this after update to `@progress/kendo-angular-popup@1.3.2`

```
Unhandled Promise rejection: ViewDestroyedError: Attempt to use a destroyed view: detectChanges ; Zone: <root> ; Task: Promise.then ; Value: Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (core.js:9780)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14637)
    at checkAndUpdateView (core.js:13787)
    at callWithDebugContext (core.js:15041)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (core.js:14578)
    at ViewRef_.detectChanges (core.js:11559)
    at PopupComponent.reposition (popup.component.js:275)
    at ZoneDelegate.invoke (zone.js:388)
    at Zone.run (zone.js:138)
    at eval (zone.js:858) Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
    at viewDestroyedError (webpack-internal:///../../../core/esm5/core.js:9995:12)
    at Object.debugUpdateDirectives [as updateDirectives] (webpack-internal:///../../../core/esm5/core.js:14852:15)
    at checkAndUpdateView (webpack-internal:///../../../core/esm5/core.js:14002:14)
    at callWithDebugContext (webpack-internal:///../../../core/esm5/core.js:15256:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (webpack-internal:///../../../core/esm5/core.js:14793:12)
    at ViewRef_.detectChanges (webpack-internal:///../../../core/esm5/core.js:11774:22)
    at PopupComponent.reposition (webpack-internal:///../../../../@progress/kendo-angular-popup/dist/es/popup.component.js:283:23)
    at ZoneDelegate.invoke (webpack-internal:///../../../../zone.js/dist/zone.js:388:26)
    at Zone.run (webpack-internal:///../../../../zone.js/dist/zone.js:138:43)
    at eval (webpack-internal:///../../../../zone.js/dist/zone.js:858:57)
```

**Comment by danielkaradachki** [comment]
Indeed, the issue is with the popup:
https://plnkr.co/edit/sys2HijbAcj4ZCNElzCT?p=preview
A dev version(1.3.3-dev.201801170947) with a fix is now available. Apologies for the inconveniences caused.

**Comment by adapaGangadhara** [comment]
I am facing the same Issue. 
I have created a grid which contains multi-select drop down inside the gird column I was able to populate the drop down but the error appears when popover closed after selecting the values in the multi-select drop down

I have tried installing the “@progress/kendo-angular-popup@1.3.3” but the issue is not resolved.

![viewdestroyerror](https://user-images.githubusercontent.com/32499648/35159870-9b9da072-fd09-11e7-9531-7d35581e2277.PNG)

**Comment by mihaislobozeanu** [comment]
Hi,
I'm facing the same issue with drop-downs, but only when popup direction is up. `reposition` method on `PopupComponent` does not check whether the `_cdr` is destroyed or not.

**Comment by danielkaradachki** [comment]
The latest version of the popup package(1.3.3) should fix the issue and I am unable to replicate the error with it. If the issue persists with the latest version, please provide a runnable sample so I can investigate further.

**Comment by ilianiv** [comment]
1.3.3 fixes the problem in our project. Thanks!
