### ISSUE TITLE
Possible issue with webpack & Kendo Grid 

### ISSUE THREAD

**Issue by dcparsons** [telerik/kendo-angular#260]
I am using [this](http://blog.stevensanderson.com/2016/10/04/angular2-template-for-visual-studio/) template for Visual Studio which uses ASP.NET Core & Angular2 with webpack.  After cleaning up a bunch of issues with webpack related to upgrading most of the packages, I have run into an issue with the Kendo Grid, but I am not sure if the problem is with webpack, kendo, how the two play together, or how the template has things configured.  Since the error I am receiving is originating within kendo scripts I figured I would start here.  What I will say is that if I were to remove webpack and put SystemJS in place, this code just works.  

The below view is part of my default route and the contents are displayed via a `<router-outlet></router-outlet>`

```
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h2 class="page-title">Dealers</h2>
            <kendo-grid [data]="gridDataSource"
                        [pageSize]="10"
                        [skip]="skip"
                        [sortable]="{ mode: 'single' }"
                        [sort]="sort"
                        [pageable]="{
                                        buttonCount: '5',
                                        info: 'true',
                                        type: 'numeric',
                                        pageSizes: [10, 25, 50, 75, 100],
                                        previousNext: 'true'
                                   }"
                        [scrollable]="none"
                        (sortChange)="sortChange($event)"
                        (pageChange)="pageChange($event)">
                <kendo-grid-column field="DealerNumber" title="Dealer Number">
                    <template kendoGridCellTemplate let-dataItem>
                        <a [routerLink]="['/dealer', dataItem.DealerNumber]">{{dataItem.DealerNumber}}</a>
                    </template>
                </kendo-grid-column>
                <kendo-grid-column field="DealerName" title="Dealer Name">
                </kendo-grid-column>
                <kendo-grid-column field="IsCim" title="CIM+ Dealer">
                    <template kendoGridCellTemplate let-dataItem>
                        {{dataItem.IsCim ? "Yes" : "No"}}
                    </template>
                </kendo-grid-column>
                <kendo-grid-column field="CurrentCIMOrderStatus" title="Daily CIM+ Order Status">
                </kendo-grid-column>
            </kendo-grid>
        </div>
    </div>
</div>

```

There isn't anything fancy here, and the component code is equally unremarkable.  Now as part of the Visual Studio template there are two webpack.config files: one that constantly runs as you make changes to the application and one (webpack.config.vendor.js) I call manually when i add third party vendor packages to my application.  These vendor packages are then bundled up for use in the application.  The packages/files that I include in the vendor file are as follows:

```
'@angular/common',
            '@angular/compiler',
            '@angular/core',
            '@angular/http',
            '@angular/forms',
            '@angular/platform-browser',
            '@angular/platform-browser-dynamic',
            '@angular/router',
            '@angular/platform-server',
            '@ng-bootstrap/ng-bootstrap',
            '@progress/kendo-angular-buttons',
            '@progress/kendo-angular-dialog',
            '@progress/kendo-angular-grid',
            '@progress/kendo-angular-inputs',
            '@progress/kendo-angular-intl',
            '@progress/kendo-angular-popup',
            '@progress/kendo-data-query',
            'angular2-universal',
            'angular2-universal-polyfills',
            'bootstrap/dist/css/bootstrap.css',
            'core-js',
            'es6-shim',
            'es6-promise',
            'jquery',
            'rxjs',
            'reflect-metadata',
            'octicons/build/sprite.octicons.svg',
            'zone.js'
```
Now, if I run my code as is I receive the following error (this is being thrown by .NET likely because we are prerendering)

```
An unhandled exception occurred while processing the request.
Exception: Call to Node module failed with error: TypeError: Invalid event target
at Function.FromEventObservable.setupSubscription (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\observable\FromEventObservable.js:113:19)
at FromEventObservable._subscribe (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\observable\FromEventObservable.js:135:29)
at FromEventObservable.Observable._trySubscribe (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\Observable.js:57:25)
at FromEventObservable.Observable.subscribe (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\Observable.js:45:27)
at MapOperator.call (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\operator\map.js:54:23)
at Observable.subscribe (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\Observable.js:42:22)
at DoOperator.call (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\operator\do.js:63:23)
at Observable.subscribe (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\rxjs\Observable.js:42:22)
at ListComponent.ngAfterViewInit (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\@progress\kendo-angular-grid\dist\npm\list.component.js:122:14)
at AppView.View_GridComponent2.detectChangesInternal (/GridModule/GridComponent/component.ngfactory.js:538:73)
at AppView.detectChanges (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\@angular\core\bundles\core.umd.js:12738:18)
at ViewContainer.detectChangesInNestedViews (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\@angular\core\bundles\core.umd.js:12996:41)
at AppView.View_GridComponent0.detectChangesInternal (/GridModule/GridComponent/component.ngfactory.js:925:14)
at AppView.detectChanges (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\@angular\core\bundles\core.umd.js:12738:18)
at AppView.internalDetectChanges (D:\dev\Cim Order Mgmt\Dashboard\Development\Trunk\Dashboard\node_modules\@angular\core\bundles\core.umd.js:12723:22)
```

As you can see this bubbles up through the `Grid` and `ListComponents`.  Now if I remove the entire `<kendo-grid>` from my view and run my app the shell of my UI displays correctly and no error is generated.  Here is the strange part: if I add the `<kendo-grid>` back into the view through Visual Studio and click Save, webpack rebuilds the main bundle and pushes the change to the browser.  In this instance the kendo-grid **DOES** display on screen.  However, if I refresh the browser in any way I receive the error I mentioned previously.

Does anyone have any thoughts about this?

Angular: "~2.4.4"
Kendo Grid: "^0.13.1"
webpack : "^2.2.1"

**Comment by tsvetomir** [comment]
What version of rxjs are you referencing? It should be `"rxjs": "^5.0.1"`

**Comment by dcparsons** [comment]
I was using a newer version of rxjs, however changing it to `^5.0.1` did not correct the problem.  I am working on a much scaled down repo right now to see if I can recreate the problem with a minimal amount of dependencies.  I will post the repo later on today if the problem persists.

**Comment by dcparsons** [comment]
Apologies for the delay, it has been a terribly hectic day.  I was able to get the following template to display properly in a browser:

```
<div class="container-fluid">
    <kendo-grid>
        <kendo-grid-column field="ColumnA" title="Column A">
        </kendo-grid-column>
        <kendo-grid-column field="ColumnB" title="Column B">
        </kendo-grid-column>
    </kendo-grid>
</div>
```

Using webpack (^2.2.1) and the webpack-dev-server (2.2.0-rc.0) along with these dependencies:

```
  "dependencies": {
    "@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "@progress/kendo-angular-grid": "^0.13.1",
    "@progress/kendo-data-query": "^0.3.4",
    "@progress/kendo-angular-intl": "^0.9.0",
    "@types/node": "^7.0.4",
    "core-js": "^2.4.1",
    "rxjs": "5.0.1",
    "zone.js": "^0.7.4"
  },
```

I am going to continue investigating the issue but I don't know that it makes sense to keep this issue open here (at least for now) so I am going to close it.  If I wind up with something more definitive I will open an issue here or with the respective project.
