### ISSUE TITLE
Extending Kendo Angular GridComponent

### ISSUE THREAD

**Issue by JozanBaybars** [telerik/kendo-angular#3142]
I'm trying to extend the GridComponent and one of its dependencies is the `ChangeDetectorRef`.

```
export class BgridComponent extends GridComponent implements OnInit {

  @Input() exportFileName: string = '';

  constructor(
    ...,
    changeDetectorRef: ChangeDetectorRef,
    ...
  ){
    super(
      ...,
      changeDetectorRef,
      ...
    )
  }
}
```

When I provide it in the `super` call, it gives me an error

```
ERROR NullInjectorError: StaticInjectorError(AppModule)[BgridComponent -> ChangeDetectorRef]: 
  StaticInjectorError(Platform: core)[BgridComponent -> ChangeDetectorRef]: 
    NullInjectorError: No provider for ChangeDetectorRef!
    at NullInjector.get (http://localhost:4400/vendor.js:45947:27)
    at resolveToken (http://localhost:4400/vendor.js:60865:24)
    at tryResolveToken (http://localhost:4400/vendor.js:60791:16)
    at StaticInjector.get (http://localhost:4400/vendor.js:60641:20)
    at resolveToken (http://localhost:4400/vendor.js:60865:24)
    at tryResolveToken (http://localhost:4400/vendor.js:60791:16)
    at StaticInjector.get (http://localhost:4400/vendor.js:60641:20)
    at resolveNgModuleDep (http://localhost:4400/vendor.js:71828:29)
    at _createClass (http://localhost:4400/vendor.js:71898:68)
    at _createProviderInstance (http://localhost:4400/vendor.js:71861:26)
```

 - OS: Windows 10
 - Browser: Chrome, Edge

**Comment by mbechev** [comment]
Hi @JozanBaybars,

Indeed extending existing components is not a recommended way. Apart from ChangeDetectorRef, the GridComponent expects other services to be provided, which has its own services in their constructors.

Creating custom wrapper components, or directives are the preferred approach if you want to set default Grid configurations (or any other custom configurations).

**Comment by JozanBaybars** [comment]
Actually I've added all providers for all services but the ChangeDetectorRef is not a provider.

I'm facing a very complex and generic use cases, for that I'm badly need to extend it.

**Comment by mbechev** [comment]
Hi @JozanBaybars,

I understand the situation that you are in, but if you have any additional questions, please open a [support ticket](https://www.telerik.com/account/support-tickets) for assistance with implementing specific scenarios or configuration.
