### ISSUE TITLE
[Grid] Jest TypeError: Class constructor EventEmitter_ cannot be invoked without 'new'

### ISSUE THREAD

**Issue by FloppyNotFound** [telerik/kendo-angular#3660]
**Describe the bug**
When running Jest tests on a component which includes the Kendo Grid in the latest version v7.0, the following error is thrown:

TypeError: Class constructor EventEmitter_ cannot be invoked without 'new'

      at new Wt (node_modules/@progress/kendo-angular-grid/bundles/kendo-angular-grid.umd.
      at new R (node_modules/@progress/kendo-angular-grid/bundles/kendo-angular-grid.umd.j
      at NodeInjectorFactory.R_Factory [as factory] (ng:\R\ɵfac.js:5:10)
      at getNodeInjectable (node_modules/@angular/core/fesm2015/core.mjs:3565:44)
      at instantiateAllDirectives (node_modules/@angular/core/fesm2015/core.mjs:10320:27)
      at createDirectivesInstances (node_modules/@angular/core/fesm2015/core.mjs:9649:5)
      at ɵɵelementStart (node_modules/@angular/core/fesm2015/core.mjs:14566:9)
      at ɵɵelement (node_modules/@angular/core/fesm2015/core.mjs:14621:5)
      at HomeComponent_Template (ng:/HomeComponent.js:6:21)
      at executeTemplate (node_modules/@angular/core/fesm2015/core.mjs:9620:9)
      at renderView (node_modules/@angular/core/fesm2015/core.mjs:9423:13)
      at renderComponent$1 (node_modules/@angular/core/fesm2015/core.mjs:10727:5)
      at renderChildComponents (node_modules/@angular/core/fesm2015/core.mjs:9288:9)
      at renderView (node_modules/@angular/core/fesm2015/core.mjs:9448:13)
      at renderComponent$1 (node_modules/@angular/core/fesm2015/core.mjs:10727:5)
      at renderChildComponents (node_modules/@angular/core/fesm2015/core.mjs:9288:9)
      at renderView (node_modules/@angular/core/fesm2015/core.mjs:9448:13)
      at ComponentFactory.create (node_modules/@angular/core/fesm2015/core.mjs:21639:13)
      at initComponent (node_modules/@angular/core/fesm2015/testing.mjs:1773:51)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundlndle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bunbundle.umd.js:3803:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundlndle.umd.js:408:56)
      at Object.onInvoke (node_modules/@angular/core/fesm2015/core.mjs:25592:33)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundlndle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundl
      at NgZone.run (node_modules/@angular/core/fesm2015/core.mjs:25446:28)
      at TestBedRender3.createComponent (node_modules/@angular/core/fesm2015/testing.mjs:1
      at Function.createComponent (node_modules/@angular/core/fesm2015/testing.mjs:1617:37
      at src/app/app.component.spec.ts:21:29
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundlndle.umd.js:409:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/bunbundle.umd.js:3803:43)
      at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invoke (node_modules/zone.js/bundlndle.umd.js:408:56)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/bundles/zone-testing-bundl
      at Object.wrappedFunc (node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4288:

**To Reproduce**

- Extract the attached file "ng-jest-preset-error.zip"
- Run "yarn" or "npm install" in th extracted folder to install the npm packages
- Run "yarn test" or "npm run test" to start the tests

**Expected behavior**
The tests are run and the test result is visible as an output, without the mentioned error being displayed.

**Browser**
n/a

**Additional context**
I learnt in my research that Jest Preset was not working with Kendo Grid because of the component not being Ivy-optimized, but this issue was addressed in the release of Grid v7.0 (https://github.com/telerik/kendo-angular/issues/3502).
Unfortunately, it is still not working with the latest Grid version 7.

Similar issues I found on the internet:

- https://stackoverflow.com/questions/71564898/jest-kendo-angular-grid-class-constructor-eventemitter-cannot-be-invoked-w
- https://stackoverflow.com/questions/62692676/error-typeerror-class-constructor-eventemitter-cannot-be-invoked-without-new

[ng-jest-preset-error.zip](https://github.com/telerik/kendo-angular/files/8570392/ng-jest-preset-error.zip)

**Comment by dtopalov** [comment]
The jest preset, when used with Angular v13, is only compatible with libraries built specifically for this version of Angular. The details are boring, but basically all referenced libraries should contain only ES modules. This would make the libraries incompatible with v12.

For the time being, this setup will only work with v12, as demonstrated in [this fork](https://github.com/tsvetomir/jest-preset-angular/tree/main/examples/example-app-v12).
This can change once we drop support for v12, which is unlikely to happen this year.

I hope this makes sense.

**Comment by vbraun** [comment]
It seems that there is only minimal use of the `ZoneAwareEventEmitter` subclass, can we just get a build that doesn't have it when running under jest? I'd rather have a version that has a minimally different behavior while testing than one that can't be tested at all. E.g.:
```
if (typeof jest === 'undefined')
    ZoneAwareEventEmitter = EventEmitter
else 
    ZoneAwareEventEmitter = ... proper subclass ...
```

**Comment by GustavoCostaW** [comment]
For those who are just testing components that use the grid (instantiating), you can mock it!

jest.mock('@progress/kendo-angular-grid');

**Comment by dtopalov** [comment]
@nadavsinai-philips all Kendo UI for Angular packages and components are compatible with Angular 13 and 14 - meaning they are functioning as expected in Angular 13 and 14 applications.

When used in Angular 13 and 14 applications, jest-preset is only compatible with libraries that contains ES modules only. Kendo UI for Angular still supports Angular 12, as it is officially under LTS, thus our packages will be incompatible with jest-preset in Angular 13 and 14 applications as long as we need to support Angular 12.

Until support for Angular 12 is dropped, the workaround suggested by @GustavoCostaW seems to be the way to go.

**Comment by nadavsinai-philips** [comment]
@GustavoCostaW , @dtopalov thanks for your reply, 
We can't simply use mock for our use of grid in test needs that the grid will actually render data.
I think that an additional build flavor with .mjs extension and ES module code could exist in addition to the ESM5,FESEM, UMD files you already have, just by adding another field (eg module) to package.json you could give this flexability of invoking a bundler/jest with code that is compatible with both APF for angular 12 and for jest etc under node

**Comment by nadavsinai-philips** [comment]
@dtopalov thanks for your work and script, I will try to integrate this, looks like an OK workaround for me

**Comment by angelnikolov** [comment]
Has this been solved? I am experiencing this in a large project using `kendo-angular-grid` ^7.4.2 and `angular` 14.2.0

**Comment by stanciupaul** [comment]
@dtopalov thanks, seems that running `ngcc` and `"postinstall": "node ./patch-kendo-bundles.mjs"` did the trick. Now I'm able to run tests with Jest 27 on Angular 13.

So to summarize it, I've added the `postinstall` command and run `ngcc` before executing the tests. Here are the commands:
`"postinstall": "node ./patch-kendo-bundles.mjs"`
`"test": "ngcc && ng test --no-cache"`
