### ISSUE TITLE
[Scheduler] Empty resources data throws an unhandled error in console

### ISSUE THREAD

**Issue by seb9465** [telerik/kendo-angular#3719]
**Describe the bug**
Using the scheduler, when giving an empty array to the `data` field of the `ressources` input, an unhandled error is thrown. 
Here is a copy of the error displayed in the console: 
```
Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at kendo-angular-scheduler.js:11964:141
    at Array.forEach (<anonymous>)
    at DayTimeSlotService.layoutTimeline (kendo-angular-scheduler.js:11963:21)
    at TimelineMultiDayViewComponent.reflow (kendo-angular-scheduler.js:14297:21)
    at TimelineMultiDayViewComponent.updateView (kendo-angular-scheduler.js:9585:14)
    at TimelineMultiDayViewComponent.updateView (kendo-angular-scheduler.js:12453:15)
    at ConsumerObserver.next (Subscriber.js:91:1)
    at SafeSubscriber._next (Subscriber.js:60:1)
    at SafeSubscriber.next (Subscriber.js:31:1)
    at subscribe.innerSubscriber (switchMap.js:14:104)
```
Here's the basics of our implementation of our scheduler : 
**In our template**
```
<kendo-scheduler
  ...
  [ressources]="schedulerResources"
  ...
></kendo-scheduler>
```
**In our component**
```
schedulerResources = [
  {
    ...,
    data: [],    // Here's were it all starts. If I give an empty array, it errors. If the array is not empty, it does not error.
    ...
  }
];
```

**Expected behavior**
It should not throw an error. Scheduler should display without data.

**Comment by svetq** [comment]
closing this issue in favor of https://github.com/telerik/kendo-angular/issues/3726
