### ISSUE TITLE
Issue loading the Inputs module

### ISSUE THREAD

**Issue by dpdragnev** [telerik/kendo-angular#398]
Hello,

I am using SystemJS to load the modules and I am getting an error when I try loading the Inputs module.  Here is my setup:
systemjs.config.js:
```
(function (global) {
	System.config({
		baseURL: '.',
		paths: {
			// paths serve as alias
			'npm:': 'node_modules/'
		},
		// map tells the System loader where to look for things
		map: {
			// our app is within the app folder
			app: 'app',

			// angular bundles
			'@angular/core': 'npm:@angular/core/bundles/core.umd.js',
			'@angular/common': 'npm:@angular/common/bundles/common.umd.js',
			'@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
			'@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
			'@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
			'@angular/http': 'npm:@angular/http/bundles/http.umd.js',
			'@angular/router': 'npm:@angular/router/bundles/router.umd.js',
			'@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

			//kendo components
			'@progress/kendo-angular-l10n': 'npm:@progress/kendo-angular-l10n',
			'@progress/kendo-angular-intl': 'npm:@progress/kendo-angular-intl',
			'@progress/kendo-angular-grid': 'npm:@progress/kendo-angular-grid',
			'@progress/kendo-angular-dateinputs': 'npm:@progress/kendo-angular-dateinputs',
			'@progress/kendo-angular-buttons': 'npm:@progress/kendo-angular-buttons',
			'@progress/kendo-angular-dropdowns': 'npm:@progress/kendo-angular-dropdowns',
			'@progress/kendo-angular-inputs': 'npm:@progress/kendo-angular-inputs',
			'@progress/kendo-popup-common': 'npm:@progress/kendo-popup-common',
			'@progress/kendo-angular-popup': 'npm:@progress/kendo-angular-popup',
			'@progress/kendo-data-query': 'npm:@progress/kendo-data-query',
			'@progress/kendo-date-math': 'npm:@progress/kendo-date-math',

			'@telerik/kendo-intl': 'npm:@telerik/kendo-intl',
			'@telerik/kendo-draggable': 'npm:@telerik/kendo-draggable',
			'@telerik/kendo-dropdowns-common': 'npm:@telerik/kendo-dropdowns-common',
			'@telerik/kendo-inputs-common': 'npm:@telerik/kendo-inputs-common',
			

			// other libraries
			'rxjs': 'npm:rxjs',
			'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
			'ng-block-ui': 'npm:ng-block-ui/bundles/umd',
			'ng2-toasty': 'npm:ng2-toasty/bundles/index.umd.js'
		},
		// packages tells the System loader how to load when no filename and/or no extension
		packages: {
			app: {
				defaultExtension: 'js'
			},
			rxjs: {
				defaultExtension: 'js'
			},
			'ng-block-ui': { main: 'index.js', defaultExtension: 'js' },
			'@telerik/kendo-draggable': { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@telerik/kendo-intl': { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@progress/kendo-angular-intl': { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@progress/kendo-data-query': { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@progress/kendo-angular-l10n': { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-grid": { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-dateinputs": { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-buttons": { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-dropdowns": { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-inputs": { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@progress/kendo-popup-common': { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-angular-popup": { main: './dist/npm/main.js', defaultExtension: 'js' },
			"@progress/kendo-date-math": { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@telerik/kendo-dropdowns-common': { main: './dist/npm/main.js', defaultExtension: 'js' },
			'@telerik/kendo-inputs-common': { main: './dist/npm/main.js', defaultExtension: 'js' }
		}
	});
})(this);
```

app.module.ts:
```
...
//kendo
import { GridModule } from '@progress/kendo-angular-grid';
import { ButtonsModule } from '@progress/kendo-angular-buttons';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { InputsModule } from '@progress/kendo-angular-inputs';
import { PopupModule } from '@progress/kendo-angular-popup';
import { DropDownsModule } from '@progress/kendo-angular-dropdowns';

...

imports: [
		RouterModule.forRoot(appRoutes),
		BrowserModule,
		FormsModule,
		BlockUIModule,
		HttpModule,
		GridModule,
		ButtonsModule,
		DateInputsModule,
		InputsModule,
		PopupModule,
		DropDownsModule,
		ToastyModule.forRoot()
	],
```

I am getting the following error if I try to run the app:
```
"Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/slider.module.js:8:37)
	    at eval (http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/slider.module.js:59:4)
	    at eval (http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/slider.module.js:60:3)
	    at eval (<anonymous>)
	Evaluating http://dev-unicorn2.com/@progress/kendo-angular-resize-sensor
	Evaluating http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/slider.module.js
	Evaluating http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/inputs.module.js
	Evaluating http://dev-unicorn2.com/node_modules/@progress/kendo-angular-inputs/dist/npm/main.js
	Evaluating http://dev-unicorn2.com/app/app.module.js
	Evaluating http://dev-unicorn2.com/main.js
	Error loading http://dev-unicorn2.com/main.js
    at addToError (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:122:78) [<root>]
    at linkSetFailed (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:687:15) [<root>]
    at http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:624:9 [<root>]
    at doDynamicExecute (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:769:7) [<root>]
    at link (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:964:20) [<root>]
    at doLink (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:623:7) [<root>]
    at updateLinkSetOnLoad (http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:669:18) [<root>]
    at http://dev-unicorn2.com/node_modules/systemjs/dist/system.src.js:485:11 [<root>]
    at Zone.run (http://dev-unicorn2.com/node_modules/zone.js/dist/zone.js:126:43) [<root> => <root>]
    at http://dev-unicorn2.com/node_modules/zone.js/dist/zone.js:713:57 [<root>]
    at Zone.runTask (http://dev-unicorn2.com/node_modules/zone.js/dist/zone.js:166:47) [<root> => <root>]
    at drainMicroTaskQueue (http://dev-unicorn2.com/node_modules/zone.js/dist/zone.js:546:35) [<root>]"
```

It seems that the error is related to the Slider module.  I tried loading just the Switch module, but I am still getting the same error.

Thank you.

**Comment by tsvetomir** [comment]
How are you importing the SliderModule? It should be:

`import { SliderModule } from '@progress/kendo-angular-inputs';`

**Comment by dpdragnev** [comment]
I am importing the whole Inputs module like:
import { InputsModule } from '@progress/kendo-angular-inputs';

**Comment by dpdragnev** [comment]
I found the issue:

in the packages section of systemjs.config.js I replaced:
"@progress/kendo-angular-inputs": { main: './dist/npm/main.js', defaultExtension: 'js' },
with
"@progress/kendo-angular-inputs": { main: './**dist/cdn/js/kendo-angular-inputs.js**', defaultExtension: 'js' },

I wish the documentation was a little clearer on how to setup SystemJS.

**Comment by tsvetomir** [comment]
That should work as the cdn bundle packs all direct dependencies. It's not exactly official, but its here to stay.
