### ISSUE TITLE
[GRID] & [datetime-picker] use in ng-template kendoGridCellTemplate, edit existing date show error while datetime popup change to time tab.

### ISSUE THREAD

**Issue by snookpy** [telerik/kendo-angular#4236]
**Describe the bug**
When edit datetimepicker inside grid after seleteced date from popup and it auto change to time tab, it throw the error 

**ERROR TypeError: Cannot read properties of undefined (reading 'removeAttribute')
    at NoneEncapsulationDomRenderer.removeAttribute (dom_renderer.ts:284:6)
    at BaseAnimationRenderer.removeAttribute (renderer.ts:124:12)
    at DateTimePickerComponent.closePopup (progress-kendo-angular-dateinputs.mjs:14436:23)
    at DateTimePickerComponent.ngOnDestroy (progress-kendo-angular-dateinputs.mjs:13915:18)
    at executeOnDestroys (node_manipulation.ts:558:29)
    at cleanUpView (node_manipulation.ts:462:3)
    at destroyViewTree (node_manipulation.ts:276:3)
    at destroyLView (node_manipulation.ts:439:44)
    at ViewContainerRef.remove (view_container_ref.ts:674:1)
    at eval (ng_if.ts:18:1)**
    
I create custom column of Grid which add kendo-datetimepicker inside ng-template

here example code: https://stackblitz.com/edit/angular-sntkpr?file=src%2Fapp%2Fproducts.ts,src%2Fapp%2Fproducts.service.ts,src%2Fapp%2Fapp.component.ts

**To Reproduce**
1. Click Edit date column code from above.
2. Select column Date for editing then it show Popup for select Datetime.
3. After select some date it auto go to Time tab and it throw error.

**Screenshots**

https://github.com/telerik/kendo-angular/assets/16642760/ee916754-5e63-4df6-9a03-669b62674833

**Browser**
 - OS: Macos
 - Browser Chrome
 - Version [for example, 22]

```[tasklist]
### Tasks
```

**Comment by mbechev** [comment]
The fix is available in [`v15.5.0`](https://www.telerik.com/kendo-angular-ui/components/changelogs/kendo-angular-ui/#v15.5.0).
