### ISSUE TITLE
[Grid][TreeList] Destroying the component through routing sometimes causes an error

### ISSUE THREAD

**Issue by dtopalov** [telerik/kendo-angular#4497]
### Description

When the Grid component is destroyed by the Angular routing mechanism, sometimes the following error is observed:

```
core.mjs:6531 ERROR TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at ch.notify (progress-kendo-angular-grid.mjs:527:118)
    at lv.ngOnDestroy (progress-kendo-angular-grid.mjs:26749:62)
    at wp (core.mjs:10462:32)
    at lg (core.mjs:10365:9)
    at DD (core.mjs:10193:21)
    at t2 (core.mjs:10338:9)
    at Vm.destroy (core.mjs:13127:9)
    at lk.destroy (core.mjs:15920:23)
    at Bt.deactivate (router.mjs:2544:28)
    at as.deactivateRouteAndOutlet (router.mjs:3072:32)
```

This seems to be caused by code in the **GridToolbarNavigationService** `notify` method.

### Steps To Reproduce

I have an angular routerlink to switch between two components (source and target) with kendo grid:

When I click the routerlink to navigate to new component, the router tries to destroy the source component and kendo grid like it should.

### Actual Behavior

Sometimes the described error is thrown before destroying the host component.

### Expected Behavior

No JavaScript error should be triggered.

### Browser

Chrome

### Browser version

latest

### OS type

MacOS

**Comment by tswetti** [comment]
The fix is available in dev version - 17.2.1-develop.2

https://www.telerik.com/kendo-angular-ui/components/installation/development-builds
