### ISSUE TITLE
Grid Excel Export not working!

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular#496]
PDF export with the same Grid works fine.

I get the following error while trying the Excel Export:

ERROR TypeError: __webpack_require__.i(...)(...).then is not a function
    at ExcelComponent.exportData (http://localhost:50333/vendor.dll.js:420720:125)
    at exportData (http://localhost:50333/vendor.dll.js:420693:19)
    at ExcelComponent.save (http://localhost:50333/vendor.dll.js:420702:13)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:50333/vendor.dll.js:4120:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:50333/vendor.dll.js:101478:16)
    at SafeSubscriber.next (http://localhost:50333/vendor.dll.js:101427:22)
    at Subscriber._next (http://localhost:50333/vendor.dll.js:101380:26)
    at Subscriber.next (http://localhost:50333/vendor.dll.js:101344:18)
    at EventEmitter.Subject.next (http://localhost:50333/vendor.dll.js:107777:25)....

Do you have any ideas?

Versions:
- Angular: 4.0.3
- Kendo Grid: 0.29.0
- Excel-Export: 0.1.0

**Comment by danielkaradachki** [comment]
Could you provide a runnable sample that demonstrates the problem? The excel export seems to be working in the [demos](http://www.telerik.com/kendo-angular-ui/components/grid/excel-export/).

**Comment by simon11196** [comment]
We copied the demo in a test component in our project and got the error mentioned in our 1st post. 
We tried to recreate it in a plunker, without success... (works fine there)

Could it be related to webpack?
We use the following versions:

"webpack": "2.3.1",
"webpack-dev-middleware": "1.10.0",
"webpack-dev-server": "2.4.2",
 "webpack-dll-bundles-plugin": "1.0.0-beta.5",
"webpack-merge": "3.0.0"

**Comment by danielkaradachki** [comment]
I am not sure what webpack configuration could cause this. The only case I can think of that would cause this error is if jszip < 3.0 is somehow loaded, but we require jszip  3.1 or higher as dependency. Could you check what is the installed version? If it is the correct one then I will need a runnable project in order to investigate further. You can submit a support ticket within our (Telerik) ticketing system, if the project cannot be shared here.

**Comment by simon11196** [comment]
You were right! We used JSZip 2.6.1. After updating to 3.1.3 it works! Thanks
