### ISSUE TITLE
Can't resolve all parameters for ButtonDirective

### ISSUE THREAD

**Issue by MaklaCof** [telerik/kendo-angular#521]
I started new application with Angular 2.4.5 and tried to add button component. I get error when running application:

> Can't resolve all parameters for ButtonDirective: ([object Object], ?, [object Object], [object Object]).

My buttons versions is 0.25.1 : 

> "@progress/kendo-angular-buttons": "^0.25.1".

Call stack:
```
Error: Can't resolve all parameters for ButtonDirective: ([object Object], ?, [object Object], [object Object]).
    at SyntaxError.ZoneAwareError (http://localhost:50373/dist/vendor.js:67283:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:50373/dist/vendor.js:97820:16)
    at new SyntaxError (http://localhost:50373/dist/vendor.js:20571:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:50373/dist/vendor.js:32740:31)
    at CompileMetadataResolver._getTypeMetadata (http://localhost:50373/dist/vendor.js:32615:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:50373/dist/vendor.js:32255:24)
    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:50373/dist/vendor.js:32131:23)
    at http://localhost:50373/dist/vendor.js:32332:54
    at Array.forEach (native)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (http://localhost:50373/dist/vendor.js:32331:41)
    at http://localhost:50373/dist/vendor.js:72605:58
    at Array.forEach (native)
    at JitCompiler._loadModules (http://localhost:50373/dist/vendor.js:72604:43)
    at JitCompiler._compileModuleAndComponents (http://localhost:50373/dist/vendor.js:72559:52)
    at JitCompiler.compileModuleAsync (http://localhost:50373/dist/vendor.js:72525:21)
```

My app.module.ts source:
```
import { ButtonsModule } from '@progress/kendo-angular-buttons';


@NgModule({
    bootstrap: [ AppComponent ],
    declarations: [
        AppComponent,
        NavMenuComponent,
        CounterComponent,
        FetchDataComponent,
        HomeComponent
    ],
    imports: [
        UniversalModule, // Must be first import. This automatically imports BrowserModule, HttpModule, and JsonpModule too.
        RouterModule.forRoot([
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', component: HomeComponent },
            { path: 'counter', component: CounterComponent },
            { path: 'fetch-data', component: FetchDataComponent },
            { path: '**', redirectTo: 'home' }
        ]),
        ButtonsModule
    ]
})
export class AppModule {
}
```
And my html: `<button kendoButton [primary]="true">My Kendo UI Button</button>`

Is there any min Angular version that must be used with Kendo?

**Comment by rkonstantinov** [comment]
All of the current packages has dependency on Angular 4.x 

List of package versions which supports Angular 2.x can be found [here](https://github.com/telerik/kendo-angular/issues/469).
