### ISSUE TITLE
Grid - Grouping a column with empty data is not possible

### ISSUE THREAD

**Issue by vivek201** [telerik/kendo-angular#693]
[http://plnkr.co/edit/VHhPbB5VquLF1lq7cuur?p=preview](http://plnkr.co/edit/VHhPbB5VquLF1lq7cuur?p=preview)
If you try grouping by the column "Unit Price", the grouping works fine.

But if you try grouping by "Category", the grouping breaks
![image](https://user-images.githubusercontent.com/12758783/27585046-4719969c-5b5a-11e7-8362-66b08b382979.png)
and I get a console error:

```
ERROR TypeError: Cannot read property 'CategoryName' of undefined
    at eval (eval at t.getter (http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-data-query/dist/cdn/js/kendo-data-query.js), <anonymous>:3:18)
    at eval (http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-data-query/dist/cdn/js/kendo-data-query.js:1:10671)
    at eval (http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-data-query/dist/cdn/js/kendo-data-query.js:1:10890)
    at Array.sort (native)
    at Array.sort (https://unpkg.com/core-js@2.4.1/client/shim.min.js:8:1354)
    at Object.t.orderBy (http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-data-query/dist/cdn/js/kendo-data-query.js:1:9359)
    at Object.t.process (http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-data-query/dist/cdn/js/kendo-data-query.js:1:9916)
    at AppComponent.loadProducts (http://run.plnkr.co/If5PVQsU5ZjUVm50/app/app.component.ts!transpiled:18:44)
    at AppComponent.groupChange (http://run.plnkr.co/If5PVQsU5ZjUVm50/app/app.component.ts!transpiled:25:14)
    at Object.eval [as handleEvent] (ng:///AppModule/AppComponent.ngfactory.js:21:27)
```

Is there a way to avoid this?

**Comment by rkonstantinov** [comment]
Thanks for the report. We will address this with the next version of `kendo-data-query` package.

**Comment by vivek201** [comment]
@siyka-marinova Has this been fixed? I tried doing the same in a recently created plunker [http://plnkr.co/edit/CzUD3ONlZhA0NyJpVtor?p=preview](http://plnkr.co/edit/CzUD3ONlZhA0NyJpVtor?p=preview) but I still can't group with an empty Category.

**Comment by tsvetomir** [comment]
Please try running `npm install @progress/kendo-data-query@dev` to obtain the dev version of the Data Query package. The bug should be fixed there and an official release is pending.
